spring:
  application:
    name: cca

  profiles:
    active: test

  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

cors:
  allowed-origins: http://localhost:5173

security:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET"
    expiration-minutes: 60
    issuer: "cca"
